// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: emailcheck/email.proto

package emailcheck

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *EmailRequest) Reset() {
	*x = EmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emailcheck_email_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRequest) ProtoMessage() {}

func (x *EmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emailcheck_email_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRequest.ProtoReflect.Descriptor instead.
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return file_emailcheck_email_proto_rawDescGZIP(), []int{0}
}

func (x *EmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type EmailValidationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid         bool   `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
	NormalizedEmail string `protobuf:"bytes,2,opt,name=normalizedEmail,proto3" json:"normalizedEmail,omitempty"`
	LocalPart       string `protobuf:"bytes,3,opt,name=localPart,proto3" json:"localPart,omitempty"`
	Domain          string `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (x *EmailValidationResponse) Reset() {
	*x = EmailValidationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emailcheck_email_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailValidationResponse) ProtoMessage() {}

func (x *EmailValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emailcheck_email_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailValidationResponse.ProtoReflect.Descriptor instead.
func (*EmailValidationResponse) Descriptor() ([]byte, []int) {
	return file_emailcheck_email_proto_rawDescGZIP(), []int{1}
}

func (x *EmailValidationResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *EmailValidationResponse) GetNormalizedEmail() string {
	if x != nil {
		return x.NormalizedEmail
	}
	return ""
}

func (x *EmailValidationResponse) GetLocalPart() string {
	if x != nil {
		return x.LocalPart
	}
	return ""
}

func (x *EmailValidationResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

var File_emailcheck_email_proto protoreflect.FileDescriptor

var file_emailcheck_email_proto_rawDesc = []byte{
	0x0a, 0x16, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2f, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22,
	0x24, 0x0a, 0x0c, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x93, 0x01, 0x0a, 0x17, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x6e,
	0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61,
	0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x50,
	0x61, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x32, 0x54, 0x0a, 0x0c, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0d, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x13, 0x2e, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x7a, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x42, 0x0a,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2d, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x75, 0x73, 0x74, 0x49, 0x47, 0x72,
	0x65, 0x4b, 0x2f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2f, 0x67, 0x6f,
	0x2f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x63, 0x68, 0x65, 0x63, 0x6b, 0xa2, 0x02, 0x03, 0x45, 0x58,
	0x58, 0xaa, 0x02, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0xca, 0x02, 0x05, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0xe2, 0x02, 0x11, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_emailcheck_email_proto_rawDescOnce sync.Once
	file_emailcheck_email_proto_rawDescData = file_emailcheck_email_proto_rawDesc
)

func file_emailcheck_email_proto_rawDescGZIP() []byte {
	file_emailcheck_email_proto_rawDescOnce.Do(func() {
		file_emailcheck_email_proto_rawDescData = protoimpl.X.CompressGZIP(file_emailcheck_email_proto_rawDescData)
	})
	return file_emailcheck_email_proto_rawDescData
}

var file_emailcheck_email_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_emailcheck_email_proto_goTypes = []interface{}{
	(*EmailRequest)(nil),            // 0: email.EmailRequest
	(*EmailValidationResponse)(nil), // 1: email.EmailValidationResponse
}
var file_emailcheck_email_proto_depIdxs = []int32{
	0, // 0: email.EmailService.ValidateEmail:input_type -> email.EmailRequest
	1, // 1: email.EmailService.ValidateEmail:output_type -> email.EmailValidationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_emailcheck_email_proto_init() }
func file_emailcheck_email_proto_init() {
	if File_emailcheck_email_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_emailcheck_email_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emailcheck_email_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailValidationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_emailcheck_email_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_emailcheck_email_proto_goTypes,
		DependencyIndexes: file_emailcheck_email_proto_depIdxs,
		MessageInfos:      file_emailcheck_email_proto_msgTypes,
	}.Build()
	File_emailcheck_email_proto = out.File
	file_emailcheck_email_proto_rawDesc = nil
	file_emailcheck_email_proto_goTypes = nil
	file_emailcheck_email_proto_depIdxs = nil
}
